import io
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER

from .. import models
from ..database import get_db

router = APIRouter(prefix="/api/reports", tags=["reports"])


@router.get("/{waterbody_id}/pdf")
def get_evidence_report_pdf(waterbody_id: str, db: Session = Depends(get_db)):
    wb = db.query(models.Waterbody).filter(models.Waterbody.id == waterbody_id).first()
    if wb is None:
        raise HTTPException(status_code=404, detail=f"Waterbody '{waterbody_id}' not found")

    priority = (
        db.query(models.PriorityScore)
        .filter(models.PriorityScore.waterbody_id == waterbody_id)
        .first()
    )
    change_point = (
        db.query(models.ChangePoint)
        .filter(models.ChangePoint.waterbody_id == waterbody_id)
        .first()
    )
    latest_seg = (
        db.query(models.SegmentationResult)
        .join(models.ImageryCapture, models.SegmentationResult.capture_id == models.ImageryCapture.id)
        .filter(models.ImageryCapture.waterbody_id == waterbody_id)
        .order_by(models.ImageryCapture.date.desc())
        .first()
    )
    causes = (
        db.query(models.CauseHypothesis)
        .filter(models.CauseHypothesis.waterbody_id == waterbody_id)
        .order_by(models.CauseHypothesis.confidence.desc())
        .all()
    )

    report_ref = f"AQR-{uuid.uuid4().hex[:10].upper()}"
    generated_at = datetime.now(timezone.utc).strftime("%d %B %Y, %H:%M UTC")
    bbox = eval(wb.bbox_geojson) if wb.bbox_geojson else None

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=18 * mm, rightMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#0a1929"), fontSize=18
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", parent=styles["Normal"], textColor=colors.HexColor("#57708a"),
        fontSize=9, alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#0c2438"), fontSize=12
    )
    body_style = ParagraphStyle("BodyStyle", parent=styles["Normal"], fontSize=9.5, leading=13)
    small_style = ParagraphStyle("SmallStyle", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#5a6b7c"))

    elements = []

    # -- Header / reference block --
    elements.append(Paragraph("AquaRevive Environmental Evidence Report", title_style))
    elements.append(Paragraph(
        "Satellite-Based Waterbody &amp; Land Degradation Assessment", subtitle_style
    ))
    elements.append(Spacer(1, 4 * mm))
    elements.append(HRFlowable(width="100%", color=colors.HexColor("#0c2438"), thickness=1.2))
    elements.append(Spacer(1, 4 * mm))

    ref_table = Table([
        ["Report Reference No.", report_ref],
        ["Generated On", generated_at],
        ["Waterbody", wb.name],
        ["Ward / Jurisdiction", wb.ward or "Not assigned"],
        ["Coordinates (bbox)", str(bbox) if bbox else "Not available"],
    ], colWidths=[50 * mm, 110 * mm])
    ref_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#57708a")),
        ("FONTNAME", (1, 0), (1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(ref_table)
    elements.append(Spacer(1, 6 * mm))

    # -- Purpose statement --
    elements.append(Paragraph(
        "This report is generated by an automated satellite-monitoring system and is intended "
        "to support -- not replace -- field verification by the relevant authority. It may be "
        "attached to an inspection request or complaint referencing the report number above.",
        ParagraphStyle("Purpose", parent=body_style, textColor=colors.HexColor("#5a3d0f"),
                       backColor=colors.HexColor("#fff8ee"), borderPadding=6),
    ))
    elements.append(Spacer(1, 6 * mm))

    # -- Segmentation summary --
    elements.append(Paragraph("1. Land Cover Assessment", heading_style))
    if latest_seg:
        seg_data = [
            ["Class", "Coverage"],
            ["Water", f"{latest_seg.water_pct or 0:.1f}%"],
            ["Vegetation", f"{latest_seg.vegetation_pct or 0:.1f}%"],
            ["Bare land", f"{latest_seg.bare_land_pct or 0:.1f}%"],
            ["Built-up", f"{latest_seg.built_up_pct or 0:.1f}%"],
        ]
        seg_table = Table(seg_data, colWidths=[80 * mm, 40 * mm])
        seg_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0c2438")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        elements.append(seg_table)
    else:
        elements.append(Paragraph("No segmentation data recorded yet for this waterbody.", body_style))
    elements.append(Spacer(1, 6 * mm))

    # -- Change-point analysis --
    elements.append(Paragraph("2. Historical Change Analysis", heading_style))
    if change_point and change_point.narrative:
        elements.append(Paragraph(change_point.narrative, body_style))
    else:
        elements.append(Paragraph(
            "No statistically significant change-point detected yet, or insufficient historical imagery.",
            body_style,
        ))
    elements.append(Spacer(1, 6 * mm))

    # -- Possible causes --
    elements.append(Paragraph("3. Possible Contributing Factors (Unverified)", heading_style))
    if causes:
        cause_data = [["Possible Cause", "Model Confidence", "Supporting Evidence"]]
        for c in causes:
            cause_data.append([
                c.cause or "-",
                f"{(c.confidence or 0) * 100:.0f}%",
                c.evidence_text or "-",
            ])
        cause_table = Table(cause_data, colWidths=[45 * mm, 30 * mm, 75 * mm])
        cause_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0c2438")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(cause_table)
    else:
        elements.append(Paragraph("No cause hypotheses generated yet.", body_style))
    elements.append(Spacer(1, 6 * mm))

    # -- Priority --
    elements.append(Paragraph("4. Restoration Priority", heading_style))
    if priority:
        elements.append(Paragraph(
            f"Priority score: <b>{priority.priority_score}/100</b> "
            f"(Rank #{priority.rank} among monitored waterbodies)", body_style
        ))
    else:
        elements.append(Paragraph("Priority score not yet computed.", body_style))
    elements.append(Spacer(1, 8 * mm))

    # -- Methodology / disclaimer footer --
    elements.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc"), thickness=0.6))
    elements.append(Spacer(1, 3 * mm))
    elements.append(Paragraph(
        "<b>Methodology:</b> Land cover derived from Copernicus Sentinel-2 imagery using a "
        "U-Net CNN model. Change detection compares same-season imagery across multiple years "
        "against a historical statistical baseline. Cause hypotheses are generated by rule-based "
        "logic, not a trained model, and require field verification before being treated as fact. "
        "This report was generated automatically and has not been reviewed by a human analyst.",
        small_style,
    ))
    elements.append(Spacer(1, 2 * mm))
    elements.append(Paragraph(f"Report reference: {report_ref} -- AquaRevive Monitoring System", small_style))

    doc.build(elements)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={report_ref}_{waterbody_id}.pdf"},
    )
